In [1]:
# autograd

import torch

x = torch.ones(2,3,requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [2]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>)


In [3]:
z = y*3 
print(z)

out = z.mean()
print(out)

tensor([[9., 9., 9.],
        [9., 9., 9.]], grad_fn=<MulBackward0>)
tensor(9., grad_fn=<MeanBackward0>)


In [4]:
a = torch.tensor([1.0],requires_grad=True)
b = a * 2
b.backward()
print(a.grad)

tensor([2.])


In [6]:
def calc(a):
    b = a*2 +1
    c = b*b
    d = c/(c+2)
    e = d.mean()
    return e

x = [1.0,2.0,3.0]
x = torch.tensor(x,requires_grad=True)
y = calc(x)
y.backward()
print(x.grad.tolist())

[0.06611571460962296, 0.018289871513843536, 0.007176725193858147]


In [11]:
# dataloader

from torchvision.datasets import MNIST
from torchvision import transforms
from torch.utils.data import DataLoader

mnist_train = MNIST("./data",train=True,download=True, transform=transforms.ToTensor())
mnist_test = MNIST("./data",train=False,download=True, transform=transforms.ToTensor())

print("#　train : ",len(mnist_train)," # test : ",len(mnist_test))

#　train :  60000  # test :  10000


In [13]:
img_size = 28
batch_size = 256
train_loader = DataLoader(mnist_train,batch_size=batch_size,shuffle=True)
test_loader = DataLoader(mnist_test,batch_size=batch_size,shuffle=False)

In [ ]:
# NN model

import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        